// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGRBK1GmnRIV2AWQ_gi7tjb9zyc_uiUeE',
    appId: '1:586872962348:web:3c079b3db07525c26d0089',
    messagingSenderId: '586872962348',
    projectId: 'basica-61570',
    authDomain: 'basica-61570.firebaseapp.com',
    storageBucket: 'basica-61570.appspot.com',
    measurementId: 'G-REBW5T3CNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkXGuFwMrQdaMOo0sRsjR0UwBgRTx999w',
    appId: '1:586872962348:android:6e99e719455171096d0089',
    messagingSenderId: '586872962348',
    projectId: 'basica-61570',
    storageBucket: 'basica-61570.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg1K9eiKdm2mYNiHq0a3Rzm-ErpcJEt_s',
    appId: '1:586872962348:ios:d2142aa2eb0333b86d0089',
    messagingSenderId: '586872962348',
    projectId: 'basica-61570',
    storageBucket: 'basica-61570.appspot.com',
    iosClientId: '586872962348-5e25846bklr36njhtnd5qeg47r7fagm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.basica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg1K9eiKdm2mYNiHq0a3Rzm-ErpcJEt_s',
    appId: '1:586872962348:ios:6da44e671cc50e6e6d0089',
    messagingSenderId: '586872962348',
    projectId: 'basica-61570',
    storageBucket: 'basica-61570.appspot.com',
    iosClientId: '586872962348-hesg69d0vjqee4n6bulc2qjmadg1531s.apps.googleusercontent.com',
    iosBundleId: 'com.example.basica.RunnerTests',
  );
}
